export enum KEYENUM {
  NUMBER_0 = '0',
  NUMBER_1 = '1',
  NUMBER_2 = '2',
  NUMBER_3 = '3',
  NUMBER_4 = '4',
  NUMBER_5 = '5',
  NUMBER_6 = '6',
  NUMBER_7 = '7',
  NUMBER_8 = '8',
  NUMBER_9 = '9',
  DOT = '.',
  PLUS = '+',
  MINUS = '-',
  MULTIPLY = '*',
  DIVIDE = '/',
  EQUAL = '=',
  CLEAR = 'C',
  BACKSPACE = 'BACKSPACE',
  ESCAPE = 'ESCAPE',
  ENTER = 'ENTER',
  BLANK = '',
  POW = '**',
  FLAG_MINUS = '- / +',
}
